### ISSUE TITLE
Command and Version Issue

### ISSUE THREAD

**Issue by Dogs4Chow** [EtienneDx/RealEstate#13]
Version did not update, still shows 1.0.0
Also /re list produces an error and doesnt show plots
![image](https://user-images.githubusercontent.com/54040301/67614087-55477180-f784-11e9-9ee7-3ff32a8432c3.png)

**Comment by EtienneDx** [comment]
I haven't been able to reproduce, but did some fixes around the re list command in the version 1.1.1
