### ISSUE TITLE
Permission Wiki

### ISSUE THREAD

**Issue by joex92** [EtienneDx/RealEstate#24]
Does the plugin has some permissions?
I can't find any wiki or detailed information about the permissions...

**Comment by EtienneDx** [comment]
Hey, sorry for being this long to answer, I've been quite busy those last few months. I seem to recall implementing some permissions, but haven't created a real wiki yet. I hope to do it when I finally uppdate the code for 1.16.4 & for the lastest grifprevention.

**Comment by joex92** [comment]
ok, thanks for answering... don't sweat it out... :)

**Comment by joex92** [comment]
so, can you tell us at least what the permissions are?

**Comment by EtienneDx** [comment]
Hey, sorry for taking so long to come back to this, [here](https://github.com/EtienneDx/RealEstate/wiki/Permissions) is the wiki page you asked me.
