### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by joex92** [EtienneDx/RealEstate#26]
I've been looking through the source code and I've noticed that the plugin is mainly hardcoded in english...
it would be good if you could add the ability to change all the messages to any other language...
One of the servers, where I suggested adding the plugin, is in Spanish and I tried to translate all the messages I could but there are some things that cannot be translated, like the syntax for the time format or the error messages...
I suggest you to do it for the next release... I hope you update this for 1.17 when it comes out too... 

Hope you are fine and merry christmas... :)

**Comment by EtienneDx** [comment]
Hey, this looks like a great idea, I'll look into it in the next few days, and will hopefully release it by next weekend. Would you be ok to help with the translation once I'm done? I can handle French but don't think I can be of any help with Spanish ^^

**Comment by joex92** [comment]
yeah sure, I'm ok with translating to Spanish... I'll be waiting for the next release then...

**Comment by EtienneDx** [comment]
Hey guys, after much too long, I finally have some time and am working on this enhancement now. Hopefully you're still up to translate it once I get it all ready to go, let me know if you are :)

**Comment by EtienneDx** [comment]
Hey, all messages have been moved to a config file, it is now possible to entirely customise all messages :)

**Comment by joex92** [comment]
nice, I noticed... As soon as I translate it to Spanish (which would be the main lang of my server), I'll share the lang file with you...
