### ISSUE TITLE
Please add support for 1.16.4!

### ISSUE THREAD

**Issue by AviationF17** [EtienneDx/RealEstate#27]
**It's been a couple months and the plugin does not transfer to 1.16 easily whatsoever, not sure if this is the place to put the request but there's nowhere else to.**

**Comment by joex92** [comment]
I've tried the plugin in 1.16.4 Yatopia server and it works... although In other servers it throws some errors...

**Comment by LcorpOfficial** [comment]
it currently functions on 1.16.4 with some sales broken, and JSON text on the sign not formatting correctly. there was some minor changes to how JSON text is formatted which would need to be addressed is all

**Comment by joex92** [comment]
This could be updated to 1.16.5 already... pls @EtienneDx

**Comment by EtienneDx** [comment]
Alright I'll get to it tonight, I'll keep you posted, it should take me a day or two depending on how much GP has been modified since the last update

**Comment by AviationF17** [comment]
> Alright I'll get to it tonight, I'll keep you posted, it should take me a day or two depending on how much GP has been modified since the last update

Thanks!!!

**Comment by EtienneDx** [comment]
I've started the updating process and released a [first draft](https://github.com/EtienneDx/RealEstate/releases/tag/1.2.4-pre1) if you'd like to help me test it. I hope to finish this in a few days max, and add the requested languages support.

**Comment by EtienneDx** [comment]
Alright, I've tested the plugin and feel like it is ready for production, with the latest features of GP included in the new modifed jar. Your can find the new jars in the latest release

**Comment by joex92** [comment]
thanks @EtienneDx! will it work for 1.16.5 too?

**Comment by EtienneDx** [comment]
Yes, I've just tested it in 1.16.5
