### ISSUE TITLE
Color Formatting not rendering correctly on signs in 1.16.4

### ISSUE THREAD

**Issue by LcorpOfficial** [EtienneDx/RealEstate#28]
seems that color codes or some formatting is incorrect on displayed signs as of 1.2.4-pre1. Grandfathered transaction signs have old correct color formatting visually; but the transactions are busted and had to be replaced. Nothing in the log is helpful regarding this; I can provide image if helpful. (Tuinity #164 1.16.4 Server)

**Comment by EtienneDx** [comment]
An image could be helpful yes. Has this happened due to an update? If so I suppose that the transaction store had been deleted for some reasons...

**Comment by LcorpOfficial** [comment]
likely transaction store. can't confirm this. let me see if there are any old transactions remaining and get you a ss.

**Comment by LcorpOfficial** [comment]
yellow text is non functioning, but correctly formatted. broken transaction after most recent (gp only) update.

broken JSON formatting on sign is current; otherwise functions fine.

![2021-02-20_14 29 28](https://user-images.githubusercontent.com/73314328/108606569-cbfc7b00-7388-11eb-8e15-9a94a5b261cd.png)
![2021-02-20_14 33 25](https://user-images.githubusercontent.com/73314328/108606571-cc951180-7388-11eb-8e97-bba15da040d9.png)

**Comment by EtienneDx** [comment]
Alright, I've dug a little, can't test it properly yet but my guess is that the color codes are badly saved to the config file. I'll try to test a little more later on.

**Comment by EtienneDx** [comment]
Should be fixed as of 1.4.0
