### ISSUE TITLE
add renting that only gives containertrust

### ISSUE THREAD

**Issue by WaffleBits** [EtienneDx/RealEstate#29]
Hello it would be awesome if there was an option to rent without giving buildtrust only containertrust because my players want to build hotels but they are worried about people that rent rooms breaking the blocks of the room

**Comment by EtienneDx** [comment]
That's a great idea, altough I'm very busy currently. I'll try to work on it whenever I have a little time.

**Comment by joex92** [comment]
Also, would it be possible to rent different "rooms" in the same place but different altitude? or because of the nature of GP this wouldn't be possible?

**Comment by EtienneDx** [comment]
Hey, I'd love to implement this but as GP works in 2D, I can't make it work. This would be great tho so Idk, I'll have to see what can be done if I ever get 5 weeks to work on it.
I'm gonna close this for now, hopefully Gp will implement 3D claims soon and we'll have 3D rents

**Comment by joex92** [comment]
ok @EtienneDx, What about adding support for WorldGuard? It just came to my mind because WorldGuard can do 3D claims, so I was thinking it would be useful... idk... Although WG is often used "admin only", but it can still be helpful... of course, this is just a suggestion...
