### ISSUE TITLE
Ticks issue at booting?

### ISSUE THREAD

**Issue by joex92** [EtienneDx/RealEstate#31]
So every time my server boots up, I set up a timings report for 10min automatically, and I get this red results:
![image](https://user-images.githubusercontent.com/645579/119237489-b2dba580-bb02-11eb-8270-24d9aff9e92d.png)
 I don't know if this is an issue that could potentially worsen...
The server has not much activity, there are very few active rents, so idk...

**Comment by EtienneDx** [comment]
This seems to be due to the check for rents comming to expiration. I'll do the first check a minute after the server startup to lighten the load, hopefully that does the trick

**Comment by joex92** [comment]
> This seems to be due to the check for rents comming to expiration. I'll do the first check a minute after the server startup to lighten the load, hopefully that does the trick

well, It got better... thanks!
![image](https://user-images.githubusercontent.com/645579/119876816-e8f79b80-beed-11eb-8c85-ddce7f235642.png)
