### ISSUE TITLE
Sign header formatting broken

### ISSUE THREAD

**Issue by LcorpOfficial** [EtienneDx/RealEstate#33]
on newest version, sign header formatting is broken, should be gold color, instead displays artifacts.

![image](https://user-images.githubusercontent.com/73314328/120210949-5eb97b00-c1fe-11eb-942d-01fe353048e4.png)

**Comment by LcorpOfficial** [comment]
just noticed, this only happens on java 8. might not be a priority to fix.

**Comment by EtienneDx** [comment]
Hmm, I'm really confused about this, I don't know what could be causing it, I'll try to have a look into it. Maybe the symbols for the colors changed in java 8?
I'll try looking into it asap

**Comment by LcorpOfficial** [comment]
no worries, java8 is depreciated soon anyway, I feel it could be related to JSON text parsing methods?

**Comment by EtienneDx** [comment]
I think it might be linked to the [AnnotationConfig](https://github.com/EtienneDx/AnnotationConfig) I use to serialize the config file. I turn the special color characters into $ to make it easily editable, but maybe they changed which character is used as special character?
Idk I'll try looking into it whenever I have some time

**Comment by LcorpOfficial** [comment]
Hey no worries! I saw you join the server when I was asleep, haha. Sorry I missed you! My test server is on Java 8, production on 11 so the issue isn't present there. Feel free to DM me on discord if you need anything!

**Comment by LcorpOfficial** [comment]
Just an update on this related to v1.3.0; currently the formatting is still broken, however it did change HOW it was broken. currently running on version git-Airplane-73 (MC: 1.17.1) 

note: formatting is only broken on the for rent signs, [RENTED] and others are formatted fine.


![image](https://user-images.githubusercontent.com/73314328/132887734-84d78499-0125-4dc1-828c-78fe1cccbf90.png)

**Comment by EtienneDx** [comment]
This should now be done as of 1.4.0
