### ISSUE TITLE
Config.yml keeps resetting the sign header

### ISSUE THREAD

**Issue by pokemonrocks9** [EtienneDx/RealEstate#34]
the sign header in config.yml keeps resetting. first to &6[RealEstate] then after a server reboot it changes to ?6[RealEstate]
this breaks the real estates on sale for some reason. may be an issue on 1.17.1 in particular

**Comment by EtienneDx** [comment]
Thanks for reporting it, this issue is a duplicate of #28 but helped me pinpoint the problem
