### ISSUE TITLE
renewrent problem....

### ISSUE THREAD

**Issue by chspans** [EtienneDx/RealEstate#35]
If a person turns off automatic renewal of rent the claim is still re-rented when the time is up. The only way I can find to cancel renting is to enter an exit offer.

**Comment by EtienneDx** [comment]
Hmm, that's weird, first I've heard of it...
I'll try testing a little more to identify the problem more precisely.

**Comment by chspans** [comment]
> Hmm, that's weird, first I've heard of it...
> I'll try testing a little more to identify the problem more precisely.

Have we been able to confirm this is a bug or not?

**Comment by LcorpOfficial** [comment]
same issue on Paper-398, somewhat of a major issue as this is the only way someone can abandon a rental. enabling renewrent also does not seem to work since using 1.17, but renewals from beforehand are working.

**Comment by EtienneDx** [comment]
I tried to look into this again today, and couldn't reproduce, if anyone finds the exact situation causing this it would be great... I might have an idea or two but I don't really see where it could come from...

**Comment by LcorpOfficial** [comment]
I looked over the code and i'm no expert, but it almost seems that renewrent isn't being changed in the transactionstore? If I set a claim to rent for $1/1d and check it next day, even after running `/re renewrent disable` it just renews and continues the rent as if it was never set. `/re info` DOES show the accurate setting, and it seems it is ignored. I hope this helps.

**Comment by EtienneDx** [comment]
I just managed to find the issue which was due to a logic error in my code, linked to the multiple periods rent mechanism. The more I think about it, the more I consider removing some of these rarely used features which cause this kind of bugs.

**Comment by EtienneDx** [comment]
Using version 1.4.0-pre2 should resolve this issue for good. Again, if you have the opportunity to help out by testing, please update me using #43

**Comment by LcorpOfficial** [comment]
pls never remove autorenew, but maybe add a reference to it in the lang for when you purchase rent for a claim! it's so heavily used. I'll do some testing when I get a chance :)

**Comment by EtienneDx** [comment]
I didn't mean autorenew but the period feature, which forces the renting player to rent for multiple periods.

Eg. With this sign:
```
[rent]
1
1d
3
```

The renting player would pay rent every day for 3 days before the auto renew is taken into account.

**Comment by LcorpOfficial** [comment]
OH yeah idk if anyone ever uses that, but it seems unpopular

**Comment by LcorpOfficial** [comment]
Seems to be working!
I'd call this done

**Comment by EtienneDx** [comment]
Great, I'll release the final 1.4.0 today then!
