### ISSUE TITLE
[bug] renewrent doesn't seem to be working

### ISSUE THREAD

**Issue by LcorpOfficial** [EtienneDx/RealEstate#39]
/re renewrent enable|disable doesn't seem to be changing current setting on my server:

when players set renewrent to enable, it will still expire as if disabled, and disabling rentals that are already set to enable from older versions do not seem to disable and have to be manually removed with /re cancel. can diagnose further if needed.

This is a bit game-breaking for rentals in my server right now 😅

RE v1.2.2
Paper: 398 1.17.1

**Comment by EtienneDx** [comment]
I guess you don't have any error logs or anything I could use? I'll try to look into it before releasing #36, hopefully it is a minor error and I can get it fixed fast enough.

**Comment by LcorpOfficial** [comment]
None that I can identify, then again with how infrequent it happens it'd be hard to pin down unless I could figure out EXACTLY when it does this.
