### ISSUE TITLE
right-click breaks empty sign

### ISSUE THREAD

**Issue by dtrasca** [EtienneDx/RealEstate#41]
Hey, when right clicking an empty sign, I've seen that the sign automatically breaks and drops it, getting the "This claim is no longer for rent, sell or lease, sorry..." message.
Can this be prevented ?

**Comment by EtienneDx** [comment]
Hmm, I'm surprised this wasn't reported earlier, I suppose it might have something to do with your config file, but I'll look into it. Any chance your config.yml file contains something this line?
```
    SignsHeader: ~
```
or
```yaml
    SignsHeader: ''
```
Otherwise I'll dig deeper to find a fix.

**Comment by dtrasca** [comment]
Yes, my bad actually, that was the main problem, quick fix. I ve changed that.
Thank you for you fast reply. If there is any walk-around and u can change it in the next update, awesome, but still.. thank you
