### ISSUE TITLE
/re info formatting parsing incorrectly

### ISSUE THREAD

**Issue by LcorpOfficial** [EtienneDx/RealEstate#47]
![image](https://user-images.githubusercontent.com/73314328/158597768-a3912489-8abc-4284-a4fb-ddc913bc8778.png)

since color codes are suing $ in your lang file, when the re info is called it removes the first number from the cost of the rental and uses it like a color code instead

rentals are 450, 650 in this image, and it seems that $450 is using &4 color code, and $650 is using &6 color code.

**Comment by EtienneDx** [comment]
Yeah I saw that I will fix it asap, kind of got a busy week rn...

**Comment by LcorpOfficial** [comment]
no worries! just making sure you're aware. 😄
