### ISSUE TITLE
Shift + click on sign: price bug

### ISSUE THREAD

**Issue by duugagno** [EtienneDx/RealEstate#52]
![3r2](https://user-images.githubusercontent.com/102831172/161335327-738dc702-7281-40c6-9ed6-4c5f3b9a552d.png)

**Comment by SrBedrock** [comment]
Duplicate issue #47

**Comment by EtienneDx** [comment]
Thanks for reporting, this is indeed a duplicate. I'll try working on fixing this in the coming days but life has been hectic lately...
