### ISSUE TITLE
Trusted members of a claim can build on subclaims

### ISSUE THREAD

**Issue by SpencerSharkey** [EtienneDx/RealEstate#9]
It looks like you only check the owner when players interact w/ the subclaims, allowing trusted builders of the top-level claim to edit subclaims involved in transactions. This may apply to top level claims too

**Comment by EtienneDx** [comment]
I actually don't modify the classic behavior of GriefPrevention for the subclaims builds, just grant the renter/leaser build permissions and stop the owner from changing said permissions.

I'm marking this as an enhancement feature, since I'm not certain wether this really is a problem or not

**Comment by DmitryRendov** [comment]
it's default GP behavior. If you grant access to parent claim - you did it everywhere inside.

**Comment by EtienneDx** [comment]
Yes but we stop the owner of modifying a rented subclaim, but maybe we don't stop trusted players from the main claim to untrust etc on the subclaim, which would then make it an issue...

Need to investigate

**Comment by EtienneDx** [comment]
Rented subclaims now stopped inherritage from parent claim, which solves this issue (doesn't stop the command from re enabling inheritance, but then it would be a player choice
